### ISSUE TITLE
Any news on the feedback feature as shown on the website ?

### ISSUE THREAD

**Issue by dgillier** [LaraBug/LaraBug#76] opened 2022-08-15 11:22 UTC
Any news on the feedback feature as shown on the website ?

(this could be a great feature ;)

Thanks, Denis

**Comment by Cannonb4ll** [comment] 2022-08-15 11:33
Duplicate of https://github.com/LaraBug/LaraBug/issues/40#issuecomment-1214903820

**Closed by Cannonb4ll** 2022-08-15 11:33 UTC
